steps:
  # Dockerビルドを実行するステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-northeast2-docker.pkg.dev/pathway-492603/pathway-go/app:v1',
      '-f', 'backend/Dockerfile', # ここでDockerfileの場所を指定！
      '.' # ビルドコンテキスト（ルートを指定）
    ]

# 作成したイメージを Artifact Registry に保存する
images:
  - 'asia-northeast2-docker.pkg.dev/pathway-492603/pathway-go/app:v1'