services:
  api:
    build:
      target: development
    container_name: pathway-api-dev
    ports:
      - ${API_PORT}:8080
    volumes:
      - ./backend:/app
    environment:
      - DB_SOURCE=${DB_SOURCE}