# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Todo {
  id: ID!
  text: String!
  status: TodoStatus!
  user: User!
}

enum TodoStatus {
  NOT_STARTED
  IN_PROGRESS
  COMPLETED
}

type User {
  id: ID!
  name: String!
}

type DailyLog {
  date: String!
  isCompleted: Boolean!
}

type Roadmap {
  id: ID!
  title: String!
  createdAt: String!
}

type RoadmapNode {
  id: ID!
  roadmapId: ID!
  parentId: ID
  title: String!
}

type Query {
  todos: [Todo!]!
  dailyLogs(from: String!, to: String!): [DailyLog!]!
  roadmaps: [Roadmap!]!
  roadmapNodes(roadmapId: ID!): [RoadmapNode!]!
}

input NewTodo {
  text: String!
}

input UpdateTodo {
  text: String!
}

input UpdateTodoStatus {
  status: TodoStatus!
}

input NewRoadmap {
  title: String!
}

input NewRoadmapNode {
  roadmapId: ID!
  parentId: ID
  title: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
  deleteTodo(id: ID!): Todo!
  updateTodo(id: ID!, input: UpdateTodo!): Todo!
  updateTodoStatus(id: ID!, input: UpdateTodoStatus!): Todo!
  catchUpDailyLogs: Boolean!
  createRoadmap(input: NewRoadmap!): Roadmap!
  createRoadmapNode(input: NewRoadmapNode!): RoadmapNode!
  deleteRoadmapNode(id: ID!): RoadmapNode!
}
