// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EditStatusTodo struct {
	Status string `json:"status"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Status string `json:"status"`
	User   *User  `json:"user"`
}

type UpdateTodo struct {
	Text string `json:"text"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
