package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"pathway-backend/graph/model"
	"pathway-backend/internal/domain/entity"
	"pathway-backend/internal/infrastructure/middleware"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	todo, err := r.TodoService.CreateTodo(ctx, userID, input.Text)
	if err != nil {
		return nil, err
	}
	return ToModelTodo(ctx, r.Users, todo)
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (*model.Todo, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	todo, err := r.TodoService.DeleteTodo(ctx, userID, id)
	if err != nil {
		return nil, err
	}
	return ToModelTodo(ctx, r.Users, todo)
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodo) (*model.Todo, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	todo, err := r.TodoService.UpdateTodo(ctx, userID, id, input.Text)
	if err != nil {
		return nil, err
	}
	return ToModelTodo(ctx, r.Users, todo)
}

// UpdateTodoStatus is the resolver for the updateTodoStatus field.
func (r *mutationResolver) UpdateTodoStatus(ctx context.Context, id string, input model.UpdateTodoStatus) (*model.Todo, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	todo, err := r.TodoService.UpdateTodoStatus(ctx, userID, id, entity.TodoStatus(input.Status))
	if err != nil {
		return nil, err
	}
	return ToModelTodo(ctx, r.Users, todo)
}

// CatchUpDailyLogs is the resolver for the catchUpDailyLogs field.
func (r *mutationResolver) CatchUpDailyLogs(ctx context.Context) (bool, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	if err := r.LogService.CatchUp(ctx, userID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateRoadmap is the resolver for the createRoadmap field.
func (r *mutationResolver) CreateRoadmap(ctx context.Context, input model.NewRoadmap) (*model.Roadmap, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	roadmap, err := r.RoadmapService.CreateRoadmap(ctx, userID, input.Title)
	if err != nil {
		return nil, err
	}
	return ToModelRoadmap(roadmap), nil
}

// CreateRoadmapNode is the resolver for the createRoadmapNode field.
func (r *mutationResolver) CreateRoadmapNode(ctx context.Context, input model.NewRoadmapNode) (*model.RoadmapNode, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	node, err := r.RoadmapService.CreateNode(ctx, userID, input.RoadmapID, input.ParentID, input.Title)
	if err != nil {
		return nil, err
	}
	return ToModelRoadmapNode(node), nil
}

// DeleteRoadmapNode is the resolver for the deleteRoadmapNode field.
func (r *mutationResolver) DeleteRoadmapNode(ctx context.Context, id string) (*model.RoadmapNode, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	node, err := r.RoadmapService.DeleteNode(ctx, userID, id)
	if err != nil {
		return nil, err
	}
	return ToModelRoadmapNode(node), nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	todos, err := r.TodoService.GetTodos(ctx, userID)
	if err != nil {
		return nil, err
	}
	return ToModelTodos(ctx, r.Users, todos)
}

// DailyLogs is the resolver for the dailyLogs field.
func (r *queryResolver) DailyLogs(ctx context.Context, from string, to string) ([]*model.DailyLog, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	logs, err := r.LogService.GetDailyLogs(ctx, userID, from, to)
	if err != nil {
		return nil, err
	}
	return ToModelDailyLogs(logs), nil
}

// Roadmaps is the resolver for the roadmaps field.
func (r *queryResolver) Roadmaps(ctx context.Context) ([]*model.Roadmap, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	roadmaps, err := r.RoadmapService.ListRoadmaps(ctx, userID)
	if err != nil {
		return nil, err
	}
	return ToModelRoadmaps(roadmaps), nil
}

// RoadmapNodes is the resolver for the roadmapNodes field.
func (r *queryResolver) RoadmapNodes(ctx context.Context, roadmapID string) ([]*model.RoadmapNode, error) {
	userID, err := middleware.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	nodes, err := r.RoadmapService.ListNodes(ctx, userID, roadmapID)
	if err != nil {
		return nil, err
	}
	return ToModelRoadmapNodes(nodes), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
