// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catchUpDailyLogs = `-- name: CatchUpDailyLogs :exec
INSERT INTO daily_logs (user_id, log_date, is_completed)
SELECT todos.user_id,
        (todos.created_at AT TIME ZONE 'Asia/Tokyo')::date,
        bool_and(todos.status = 'COMPLETED')
FROM todos
WHERE todos.user_id = $1 and
    (todos.created_at AT TIME ZONE 'Asia/Tokyo')::date
    < (now() AT TIME ZONE 'Asia/Tokyo')::date
GROUP BY todos.user_id, (todos.created_at AT TIME ZONE 'Asia/Tokyo')::date
ON CONFLICT (user_id, log_date) DO NOTHING
`

func (q *Queries) CatchUpDailyLogs(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, catchUpDailyLogs, userID)
	return err
}

const getDailyLogs = `-- name: GetDailyLogs :many
select log_date, is_completed from daily_logs
where user_id = $1 and log_date >= $2 and log_date < $3
`

type GetDailyLogsParams struct {
	UserID    pgtype.UUID
	LogDate   pgtype.Date
	LogDate_2 pgtype.Date
}

type GetDailyLogsRow struct {
	LogDate     pgtype.Date
	IsCompleted bool
}

func (q *Queries) GetDailyLogs(ctx context.Context, arg GetDailyLogsParams) ([]GetDailyLogsRow, error) {
	rows, err := q.db.Query(ctx, getDailyLogs, arg.UserID, arg.LogDate, arg.LogDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyLogsRow
	for rows.Next() {
		var i GetDailyLogsRow
		if err := rows.Scan(&i.LogDate, &i.IsCompleted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
