// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roadmap.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNode = `-- name: CreateNode :one
insert into nodes (roadmap_id, parent_id, title)
values ($1, $2, $3)
returning id, roadmap_id, parent_id, title, created_at
`

type CreateNodeParams struct {
	RoadmapID pgtype.UUID
	ParentID  pgtype.UUID
	Title     string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode, arg.RoadmapID, arg.ParentID, arg.Title)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.ParentID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const createRoadmap = `-- name: CreateRoadmap :one
insert into roadmaps (user_id, title)
values ($1, $2)
returning id, user_id, title, created_at, updated_at
`

type CreateRoadmapParams struct {
	UserID pgtype.UUID
	Title  string
}

func (q *Queries) CreateRoadmap(ctx context.Context, arg CreateRoadmapParams) (Roadmap, error) {
	row := q.db.QueryRow(ctx, createRoadmap, arg.UserID, arg.Title)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :one
delete from nodes n
using roadmaps r
where n.id = $1
  and n.roadmap_id = r.id
  and r.user_id = $2
returning n.id, n.roadmap_id, n.parent_id, n.title, n.created_at
`

type DeleteNodeParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteNode(ctx context.Context, arg DeleteNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, deleteNode, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.ParentID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeByIDAndUser = `-- name: GetNodeByIDAndUser :one
select n.id, n.roadmap_id, n.parent_id, n.title, n.created_at
from nodes n
join roadmaps r on n.roadmap_id = r.id
where n.id = $1
  and r.user_id = $2
`

type GetNodeByIDAndUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetNodeByIDAndUser(ctx context.Context, arg GetNodeByIDAndUserParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByIDAndUser, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.ParentID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getRoadmapByIDAndUser = `-- name: GetRoadmapByIDAndUser :one
select id, user_id, title, created_at, updated_at
from roadmaps
where id = $1
  and user_id = $2
`

type GetRoadmapByIDAndUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetRoadmapByIDAndUser(ctx context.Context, arg GetRoadmapByIDAndUserParams) (Roadmap, error) {
	row := q.db.QueryRow(ctx, getRoadmapByIDAndUser, arg.ID, arg.UserID)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodesByRoadmap = `-- name: ListNodesByRoadmap :many
select n.id, n.roadmap_id, n.parent_id, n.title, n.created_at
from nodes n
join roadmaps r on n.roadmap_id = r.id
where n.roadmap_id = $1
  and r.user_id = $2
order by n.created_at
`

type ListNodesByRoadmapParams struct {
	RoadmapID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListNodesByRoadmap(ctx context.Context, arg ListNodesByRoadmapParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByRoadmap, arg.RoadmapID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.RoadmapID,
			&i.ParentID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoadmaps = `-- name: ListRoadmaps :many
select id, user_id, title, created_at, updated_at
from roadmaps
where user_id = $1
order by created_at
`

func (q *Queries) ListRoadmaps(ctx context.Context, userID pgtype.UUID) ([]Roadmap, error) {
	rows, err := q.db.Query(ctx, listRoadmaps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Roadmap
	for rows.Next() {
		var i Roadmap
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
update nodes n
set title = $1
from roadmaps r
where n.id = $2
  and n.roadmap_id = r.id
  and r.user_id = $3
returning n.id, n.roadmap_id, n.parent_id, n.title, n.created_at
`

type UpdateNodeParams struct {
	Title  string
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode, arg.Title, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.ParentID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}
