// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
insert into todos (text, user_id)
values ($1, $2)
returning id, text, status, user_id, created_at, updated_at
`

type CreateTodoParams struct {
	Text   string
	UserID pgtype.UUID
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Text, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :one
delete from todos
where id = $1 and user_id = $2
returning id, text, status, user_id, created_at, updated_at
`

type DeleteTodoParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, deleteTodo, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodos = `-- name: GetTodos :many
select id, text, status, user_id, created_at, updated_at from todos 
where user_id = $1
`

func (q *Queries) GetTodos(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
update todos
set text = $1
where id = $2 and user_id = $3
returning id, text, status, user_id, created_at, updated_at
`

type UpdateTodoParams struct {
	Text   string
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo, arg.Text, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoStatus = `-- name: UpdateTodoStatus :one
update todos
set status = $1
where id = $2 and user_id = $3
returning id, text, status, user_id, created_at, updated_at
`

type UpdateTodoStatusParams struct {
	Status TodoStatus
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodoStatus, arg.Status, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
